services:
  - type: web
    name: myworld-backend
    runtime: python
    rootDir: app/backend
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: "3.12.0"
    plan: free
    region: frankfurt
