import { Language } from "./types";

export const SUPPORTED_LANGUAGES: Language[] = [
  { code: "tr-TR", name: "Türkçe", flag: "🇹🇷" },
  { code: "en-US", name: "İngilizce (ABD)", flag: "🇺🇸" },
  { code: "en-GB", name: "İngilizce (İngiltere)", flag: "🇬🇧" },
  { code: "de-DE", name: "Almanca", flag: "🇩🇪" },
  { code: "fr-FR", name: "Fransızca", flag: "🇫🇷" },
  { code: "es-ES", name: "İspanyolca (İspanya)", flag: "🇪🇸" },
  { code: "es-MX", name: "İspanyolca (Meksika)", flag: "🇲🇽" },
  { code: "it-IT", name: "İtalyanca", flag: "🇮🇹" },
  { code: "ar-AE", name: "Arapça (BAE)", flag: "🇦🇪" },
  { code: "ar-SA", name: "Arapça (Suudi Arabistan)", flag: "🇸🇦" },
  { code: "ru-RU", name: "Rusça", flag: "🇷🇺" },
  { code: "zh-CN", name: "Çince (Basitleştirilmiş)", flag: "🇨🇳" },
  { code: "zh-TW", name: "Çince (Geleneksel)", flag: "🇹🇼" },
  { code: "ja-JP", name: "Japonca", flag: "🇯🇵" },
  { code: "ko-KR", name: "Korece", flag: "🇰🇷" },
  { code: "pt-BR", name: "Portekizce (Brezilya)", flag: "🇧🇷" },
  { code: "pt-PT", name: "Portekizce (Portekiz)", flag: "🇵🇹" },
  { code: "nl-NL", name: "Felemenkçe", flag: "🇳🇱" },
  { code: "pl-PL", name: "Lehçe", flag: "🇵🇱" },
  { code: "uk-UA", name: "Ukraynaca", flag: "🇺🇦" },
  { code: "vi-VN", name: "Vietnamca", flag: "🇻🇳" },
  { code: "th-TH", name: "Tayca", flag: "🇹🇭" },
  { code: "hi-IN", name: "Hintçe", flag: "🇮🇳" },
  { code: "sv-SE", name: "İsveççe", flag: "🇸🇪" },
  { code: "no-NO", name: "Norveççe", flag: "🇳🇴" },
  { code: "da-DK", name: "Danca", flag: "🇩🇰" },
  { code: "fi-FI", name: "Fince", flag: "🇫🇮" },
  { code: "el-GR", name: "Yunanca", flag: "🇬🇷" },
  { code: "he-IL", name: "İbranice", flag: "🇮🇱" },
  { code: "id-ID", name: "Endonezyaca", flag: "🇮🇩" },
  { code: "ms-MY", name: "Malezyaca", flag: "🇲🇾" },
  { code: "cs-CZ", name: "Çekçe", flag: "🇨🇿" },
  { code: "hu-HU", name: "Macarca", flag: "🇭🇺" },
  { code: "ro-RO", name: "Romence", flag: "🇷🇴" },
  { code: "sk-SK", name: "Slovakça", flag: "🇸🇰" },
  { code: "bg-BG", name: "Bulgarca", flag: "🇧🇬" },
  { code: "hr-HR", name: "Hırvatça", flag: "🇭🇷" },
  { code: "sr-RS", name: "Sırpça", flag: "🇷🇸" },
  { code: "sl-SI", name: "Slovence", flag: "🇸🇮" },
  { code: "et-EE", name: "Estonca", flag: "🇪🇪" },
  { code: "lv-LV", name: "Letonca", flag: "🇱🇻" },
  { code: "lt-LT", name: "Litvanca", flag: "🇱🇹" },
  { code: "tl-PH", name: "Filipince", flag: "🇵🇭" },
  { code: "fa-IR", name: "Farsça", flag: "🇮🇷" },
  { code: "ur-PK", name: "Urduca", flag: "🇵🇰" },
  { code: "bn-BD", name: "Bengalce", flag: "🇧🇩" },
  { code: "ta-IN", name: "Tamilce", flag: "🇮🇳" },
  { code: "te-IN", name: "Telugu dili", flag: "🇮🇳" },
  { code: "kn-IN", name: "Kannada dili", flag: "🇮🇳" },
  { code: "ml-IN", name: "Malayalam dili", flag: "🇮🇳" },
  { code: "mr-IN", name: "Marathi dili", flag: "🇮🇳" },
  { code: "gu-IN", name: "Gujarati dili", flag: "🇮🇳" },
  { code: "pa-IN", name: "Pencapça", flag: "🇮🇳" },
  { code: "sw-KE", name: "Svahili", flag: "🇰🇪" },
  { code: "yo-NG", name: "Yorubaca", flag: "🇳🇬" },
  { code: "ig-NG", name: "İgboca", flag: "🇳🇬" },
  { code: "ha-NE", name: "Hausa dili", flag: "🇳🇪" },
  { code: "az-AZ", name: "Azerice", flag: "🇦🇿" },
  { code: "ka-GE", name: "Gürcüce", flag: "🇬🇪" },
  { code: "hy-AM", name: "Ermenice", flag: "🇦🇲" },
  { code: "sq-AL", name: "Arnavutça", flag: "🇦🇱" },
  { code: "mk-MK", name: "Makedonca", flag: "🇲🇰" },
  { code: "bs-BA", name: "Bosnakça", flag: "🇧🇦" },
  { code: "mt-MT", name: "Maltaca", flag: "🇲🇹" },
  { code: "is-IS", name: "İzlandaca", flag: "🇮🇸" },
  { code: "ga-IE", name: "İrlandaca", flag: "🇮🇪" },
  { code: "cy-GB", name: "Galce", flag: "🇬🇧" },
  { code: "af-ZA", name: "Afrikaanca", flag: "🇿🇦" },
  { code: "zu-ZA", name: "Zuluca", flag: "🇿🇦" },
  { code: "xh-ZA", name: "Xhosaca", flag: "🇿🇦" },
  { code: "am-ET", name: "Amharca", flag: "🇪🇹" },
  { code: "so-SO", name: "Somalice", flag: "🇸🇴" },
  { code: "ne-NP", name: "Nepalce", flag: "🇳🇵" },
  { code: "si-LK", name: "Sinhalece", flag: "🇱🇰" },
  { code: "my-MM", name: "Birmanca", flag: "🇲🇲" },
  { code: "km-KH", name: "Kmerce", flag: "🇰🇭" },
  { code: "lo-LA", name: "Laoca", flag: "🇱🇦" }
];
