"""add_completed_at_to_photo_models

Revision ID: 0606426d8927
Revises: c80abd763178
Create Date: 2026-04-27 01:18:17.241826

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0606426d8927'
down_revision: Union[str, Sequence[str], None] = 'c80abd763178'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_models', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_models', 'completed_at')
    # ### end Alembic commands ###
