"""Add VenusAIAnalysisReport

Revision ID: 25c8061e5baf
Revises: 9169badf60d8
Create Date: 2026-03-15 17:39:55.134457

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '25c8061e5baf'
down_revision: Union[str, Sequence[str], None] = '9169badf60d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venus_ai_analysis_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('report_source', sa.String(), nullable=True),
    sa.Column('report_type', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('uploaded_file_name', sa.String(), nullable=True),
    sa.Column('uploaded_file_path', sa.String(), nullable=True),
    sa.Column('uploaded_file_type', sa.String(), nullable=True),
    sa.Column('uploaded_file_size', sa.Integer(), nullable=True),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('progress_pct', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('pdf_file_path', sa.String(), nullable=True),
    sa.Column('analysis_config', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venus_ai_analysis_reports_id'), 'venus_ai_analysis_reports', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venus_ai_analysis_reports_id'), table_name='venus_ai_analysis_reports')
    op.drop_table('venus_ai_analysis_reports')
    # ### end Alembic commands ###
