"""email_verification_system

Revision ID: 299cbef24782
Revises: a1b2c3d4e5f6
Create Date: 2026-05-11 21:52:07.772901

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '299cbef24782'
down_revision: Union[str, Sequence[str], None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_verifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('token_type', sa.String(length=20), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_verifications_id'), 'email_verifications', ['id'], unique=False)
    op.create_index(op.f('ix_email_verifications_token'), 'email_verifications', ['token'], unique=True)
    op.drop_index(op.f('ix_venus_ad_accounts_id'), table_name='ad_accounts')
    op.create_index(op.f('ix_ad_accounts_id'), 'ad_accounts', ['id'], unique=False)
    op.drop_index(op.f('ix_venus_ads_tasks_id'), table_name='ads_tasks')
    op.create_index(op.f('ix_ads_tasks_id'), 'ads_tasks', ['id'], unique=False)
    op.drop_index(op.f('ix_venus_ai_analysis_reports_id'), table_name='ai_analysis_reports')
    op.create_index(op.f('ix_ai_analysis_reports_id'), 'ai_analysis_reports', ['id'], unique=False)
    op.drop_index(op.f('ix_venus_ai_observations_id'), table_name='ai_observations')
    op.create_index(op.f('ix_ai_observations_id'), 'ai_observations', ['id'], unique=False)
    op.drop_index(op.f('ix_venus_campaigns_id'), table_name='campaigns')
    op.create_index(op.f('ix_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.drop_index(op.f('ix_venus_creatives_id'), table_name='creatives')
    op.create_index(op.f('ix_creatives_id'), 'creatives', ['id'], unique=False)
    op.drop_index(op.f('ix_venus_csv_imports_id'), table_name='csv_imports')
    op.create_index(op.f('ix_csv_imports_id'), 'csv_imports', ['id'], unique=False)
    op.drop_index(op.f('ix_venus_daily_metrics_id'), table_name='daily_metrics')
    op.create_index(op.f('ix_daily_metrics_id'), 'daily_metrics', ['id'], unique=False)
    op.drop_index(op.f('ix_venus_experiments_id'), table_name='experiments')
    op.create_index(op.f('ix_experiments_id'), 'experiments', ['id'], unique=False)
    op.drop_index(op.f('ix_venus_onboarding_checklists_id'), table_name='onboarding_checklists')
    op.create_index(op.f('ix_onboarding_checklists_id'), 'onboarding_checklists', ['id'], unique=False)
    op.drop_index(op.f('ix_venus_report_templates_id'), table_name='report_templates')
    op.create_index(op.f('ix_report_templates_id'), 'report_templates', ['id'], unique=False)
    op.add_column('users', sa.Column('email_verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'email_verified')
    op.drop_index(op.f('ix_report_templates_id'), table_name='report_templates')
    op.create_index(op.f('ix_venus_report_templates_id'), 'report_templates', ['id'], unique=False)
    op.drop_index(op.f('ix_onboarding_checklists_id'), table_name='onboarding_checklists')
    op.create_index(op.f('ix_venus_onboarding_checklists_id'), 'onboarding_checklists', ['id'], unique=False)
    op.drop_index(op.f('ix_experiments_id'), table_name='experiments')
    op.create_index(op.f('ix_venus_experiments_id'), 'experiments', ['id'], unique=False)
    op.drop_index(op.f('ix_daily_metrics_id'), table_name='daily_metrics')
    op.create_index(op.f('ix_venus_daily_metrics_id'), 'daily_metrics', ['id'], unique=False)
    op.drop_index(op.f('ix_csv_imports_id'), table_name='csv_imports')
    op.create_index(op.f('ix_venus_csv_imports_id'), 'csv_imports', ['id'], unique=False)
    op.drop_index(op.f('ix_creatives_id'), table_name='creatives')
    op.create_index(op.f('ix_venus_creatives_id'), 'creatives', ['id'], unique=False)
    op.drop_index(op.f('ix_campaigns_id'), table_name='campaigns')
    op.create_index(op.f('ix_venus_campaigns_id'), 'campaigns', ['id'], unique=False)
    op.drop_index(op.f('ix_ai_observations_id'), table_name='ai_observations')
    op.create_index(op.f('ix_venus_ai_observations_id'), 'ai_observations', ['id'], unique=False)
    op.drop_index(op.f('ix_ai_analysis_reports_id'), table_name='ai_analysis_reports')
    op.create_index(op.f('ix_venus_ai_analysis_reports_id'), 'ai_analysis_reports', ['id'], unique=False)
    op.drop_index(op.f('ix_ads_tasks_id'), table_name='ads_tasks')
    op.create_index(op.f('ix_venus_ads_tasks_id'), 'ads_tasks', ['id'], unique=False)
    op.drop_index(op.f('ix_ad_accounts_id'), table_name='ad_accounts')
    op.create_index(op.f('ix_venus_ad_accounts_id'), 'ad_accounts', ['id'], unique=False)
    op.drop_index(op.f('ix_email_verifications_token'), table_name='email_verifications')
    op.drop_index(op.f('ix_email_verifications_id'), table_name='email_verifications')
    op.drop_table('email_verifications')
    # ### end Alembic commands ###
