"""add_is_deleted_columns

Revision ID: 2b319fb8111f
Revises: 3ff8ebd4f954
Create Date: 2026-04-26 16:52:20.736096

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2b319fb8111f'
down_revision: Union[str, Sequence[str], None] = '3ff8ebd4f954'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_venus_competitors_id'), table_name='venus_competitors')
    op.drop_table('venus_competitors')
    op.add_column('calendar_events', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('notes', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('tasks', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'is_deleted')
    op.drop_column('notes', 'is_deleted')
    op.drop_column('calendar_events', 'is_deleted')
    op.create_table('venus_competitors',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('brand_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('website_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('ad_library_url', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('category', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('strengths', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('weaknesses', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('creative_style', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('venus_competitors_project_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('venus_competitors_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('venus_competitors_pkey'))
    )
    op.create_index(op.f('ix_venus_competitors_id'), 'venus_competitors', ['id'], unique=False)
    # ### end Alembic commands ###
