"""SaaS auth structure

Revision ID: 34c55783beac
Revises: e0d71e949d42
Create Date: 2026-03-13 15:16:36.112545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c55783beac'
down_revision: Union[str, Sequence[str], None] = 'e0d71e949d42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('username', sa.String(length=50), nullable=True))
    op.add_column('users', sa.Column('password_hash', sa.String(length=255), nullable=True))
    
    op.execute("UPDATE users SET username = 'bekir' WHERE id = 1")
    op.execute("UPDATE users SET username = 'user_' || id::text WHERE username IS NULL")
    op.execute("UPDATE users SET password_hash = '$2b$12$aU7A.R1wNlI8aR9aEqHPEOT.O5vK0G2v1cOQkC7rO9q3UoE4.VlXa'") # hash of 123456
    
    op.alter_column('users', 'username', nullable=False)
    op.alter_column('users', 'password_hash', nullable=False)
    
    op.drop_index('ix_users_email', table_name='users')
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.drop_column('users', 'password_hash')
    op.drop_column('users', 'username')
    # ### end Alembic commands ###
