"""add tts fields

Revision ID: 3ff8ebd4f954
Revises: 25c8061e5baf
Create Date: 2026-03-16 06:23:50.225084

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ff8ebd4f954'
down_revision: Union[str, Sequence[str], None] = '25c8061e5baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notes', sa.Column('tts_audio_url', sa.String(), nullable=True))
    op.add_column('notes', sa.Column('tts_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notes', 'tts_text')
    op.drop_column('notes', 'tts_audio_url')
    # ### end Alembic commands ###
