"""add is_completed to calendar_event

Revision ID: 65707e7aa4b3
Revises: d328dc8db1e0
Create Date: 2026-03-12 18:45:20.219307

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65707e7aa4b3'
down_revision: Union[str, Sequence[str], None] = 'd328dc8db1e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('is_completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('calendar_events', 'is_completed')
    # ### end Alembic commands ###
