"""Add revision_photo_count to color

Revision ID: 79a637927e4a
Revises: a52e00dba3b8
Create Date: 2026-04-27 12:56:13.289171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '79a637927e4a'
down_revision: Union[str, Sequence[str], None] = 'a52e00dba3b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photo_model_colors', sa.Column('revision_required', sa.Boolean(), nullable=True))
    op.add_column('photo_model_colors', sa.Column('revision_completed', sa.Boolean(), nullable=True))
    op.add_column('photo_model_colors', sa.Column('revision_completed_at', sa.DateTime(), nullable=True))
    op.add_column('photo_model_colors', sa.Column('revision_photo_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photo_model_colors', 'revision_photo_count')
    op.drop_column('photo_model_colors', 'revision_completed_at')
    op.drop_column('photo_model_colors', 'revision_completed')
    op.drop_column('photo_model_colors', 'revision_required')
    # ### end Alembic commands ###
