"""add timezone and location to users

Revision ID: 9169badf60d8
Revises: e5ce0ff9a92a
Create Date: 2026-03-15 16:56:32.880459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9169badf60d8'
down_revision: Union[str, Sequence[str], None] = 'e5ce0ff9a92a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('timezone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('location', sa.JSON(), nullable=True))
    op.drop_constraint(op.f('venus_ads_tasks_experiment_id_fkey'), 'venus_ads_tasks', type_='foreignkey')
    op.drop_constraint(op.f('venus_ads_tasks_creative_id_fkey'), 'venus_ads_tasks', type_='foreignkey')
    op.create_foreign_key(None, 'venus_ads_tasks', 'venus_experiments', ['experiment_id'], ['id'])
    op.create_foreign_key(None, 'venus_ads_tasks', 'venus_creatives', ['creative_id'], ['id'])
    op.drop_constraint(op.f('venus_creatives_experiment_id_fkey'), 'venus_creatives', type_='foreignkey')
    op.drop_constraint(op.f('venus_creatives_campaign_id_fkey'), 'venus_creatives', type_='foreignkey')
    op.create_foreign_key(None, 'venus_creatives', 'venus_campaigns', ['campaign_id'], ['id'])
    op.create_foreign_key(None, 'venus_creatives', 'venus_experiments', ['experiment_id'], ['id'])
    op.drop_constraint(op.f('venus_experiments_creative_id_fkey'), 'venus_experiments', type_='foreignkey')
    op.create_foreign_key(None, 'venus_experiments', 'venus_creatives', ['creative_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'venus_experiments', type_='foreignkey')
    op.create_foreign_key(op.f('venus_experiments_creative_id_fkey'), 'venus_experiments', 'venus_creatives', ['creative_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'venus_creatives', type_='foreignkey')
    op.drop_constraint(None, 'venus_creatives', type_='foreignkey')
    op.create_foreign_key(op.f('venus_creatives_campaign_id_fkey'), 'venus_creatives', 'venus_campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('venus_creatives_experiment_id_fkey'), 'venus_creatives', 'venus_experiments', ['experiment_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint(None, 'venus_ads_tasks', type_='foreignkey')
    op.drop_constraint(None, 'venus_ads_tasks', type_='foreignkey')
    op.create_foreign_key(op.f('venus_ads_tasks_creative_id_fkey'), 'venus_ads_tasks', 'venus_creatives', ['creative_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(op.f('venus_ads_tasks_experiment_id_fkey'), 'venus_ads_tasks', 'venus_experiments', ['experiment_id'], ['id'], ondelete='SET NULL')
    op.drop_column('users', 'location')
    op.drop_column('users', 'timezone')
    # ### end Alembic commands ###
