"""Add UserCompanyAccess and project_id to calendar and chat

Revision ID: 98716029b849
Revises: 0aef0037bd95
Create Date: 2026-05-11 18:04:41.443644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98716029b849'
down_revision: Union[str, Sequence[str], None] = '0aef0037bd95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_company_access',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('granted_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'project_id', name='uq_user_company')
    )
    op.create_index(op.f('ix_user_company_access_id'), 'user_company_access', ['id'], unique=False)
    op.add_column('calendar_events', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendar_events', 'projects', ['project_id'], ['id'])
    op.add_column('chat_sessions', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'project_id')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_column('calendar_events', 'project_id')
    op.drop_index(op.f('ix_user_company_access_id'), table_name='user_company_access')
    op.drop_table('user_company_access')
    # ### end Alembic commands ###
