"""Add ai_categories

Revision ID: ada3bd29ec2c
Revises: 65707e7aa4b3
Create Date: 2026-03-13 02:59:33.758976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada3bd29ec2c'
down_revision: Union[str, Sequence[str], None] = '65707e7aa4b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_chat_messages_session_id'), table_name='chat_messages')
    op.create_index(op.f('ix_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    op.add_column('chat_sessions', sa.Column('ai_categories', sa.JSON(), nullable=True))
    op.drop_index(op.f('idx_chat_sessions_updated'), table_name='chat_sessions')
    op.drop_index(op.f('idx_chat_sessions_user_category'), table_name='chat_sessions')
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.drop_column('chat_sessions', 'ai_category')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('ai_category', sa.VARCHAR(length=20), server_default=sa.text("'genel'::character varying"), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.create_index(op.f('idx_chat_sessions_user_category'), 'chat_sessions', ['user_id', 'ai_category'], unique=False)
    op.create_index(op.f('idx_chat_sessions_updated'), 'chat_sessions', [sa.literal_column('updated_at DESC')], unique=False)
    op.drop_column('chat_sessions', 'ai_categories')
    op.drop_index(op.f('ix_chat_messages_session_id'), table_name='chat_messages')
    op.create_index(op.f('idx_chat_messages_session_id'), 'chat_messages', ['session_id'], unique=False)
    # ### end Alembic commands ###
