"""Add photo tracking models

Revision ID: c80abd763178
Revises: 2b319fb8111f
Create Date: 2026-04-26 17:41:22.293700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c80abd763178'
down_revision: Union[str, Sequence[str], None] = '2b319fb8111f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_excel_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(), nullable=True),
    sa.Column('models_imported', sa.Integer(), nullable=True),
    sa.Column('colors_imported', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_log', sa.JSON(), nullable=True),
    sa.Column('imported_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_excel_imports_id'), 'photo_excel_imports', ['id'], unique=False)
    op.create_table('photo_models',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('sezon_kodu', sa.String(), nullable=True),
    sa.Column('model_name', sa.String(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=True),
    sa.Column('month', sa.Integer(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('delivery_date', sa.DateTime(), nullable=True),
    sa.Column('total_photos', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_models_id'), 'photo_models', ['id'], unique=False)
    op.create_table('photo_model_colors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('color_name', sa.String(), nullable=False),
    sa.Column('ig_required', sa.Boolean(), nullable=True),
    sa.Column('ig_completed', sa.Boolean(), nullable=True),
    sa.Column('ig_completed_at', sa.DateTime(), nullable=True),
    sa.Column('ig_photo_count', sa.Integer(), nullable=True),
    sa.Column('banner_required', sa.Boolean(), nullable=True),
    sa.Column('banner_completed', sa.Boolean(), nullable=True),
    sa.Column('banner_completed_at', sa.DateTime(), nullable=True),
    sa.Column('banner_photo_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['model_id'], ['photo_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_model_colors_id'), 'photo_model_colors', ['id'], unique=False)
    op.create_table('photo_revisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('color_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('revised_count', sa.Integer(), nullable=True),
    sa.Column('revised_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['color_id'], ['photo_model_colors.id'], ),
    sa.ForeignKeyConstraint(['model_id'], ['photo_models.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photo_revisions_id'), 'photo_revisions', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_photo_revisions_id'), table_name='photo_revisions')
    op.drop_table('photo_revisions')
    op.drop_index(op.f('ix_photo_model_colors_id'), table_name='photo_model_colors')
    op.drop_table('photo_model_colors')
    op.drop_index(op.f('ix_photo_models_id'), table_name='photo_models')
    op.drop_table('photo_models')
    op.drop_index(op.f('ix_photo_excel_imports_id'), table_name='photo_excel_imports')
    op.drop_table('photo_excel_imports')
    # ### end Alembic commands ###
