"""add_cross_references_note_task

Revision ID: e0d71e949d42
Revises: ada3bd29ec2c
Create Date: 2026-03-13 03:29:25.420070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0d71e949d42'
down_revision: Union[str, Sequence[str], None] = 'ada3bd29ec2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('calendar_events', sa.Column('note_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'calendar_events', 'notes', ['note_id'], ['id'])
    op.add_column('notes', sa.Column('task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'notes', 'tasks', ['task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'notes', type_='foreignkey')
    op.drop_column('notes', 'task_id')
    op.drop_constraint(None, 'calendar_events', type_='foreignkey')
    op.drop_column('calendar_events', 'note_id')
    # ### end Alembic commands ###
