"""Add live translate tables

Revision ID: f8199a6848b6
Revises: 259bddeb7bb0
Create Date: 2026-06-15 18:29:38.166783

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f8199a6848b6'
down_revision: Union[str, Sequence[str], None] = '259bddeb7bb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('live_translate_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('source_language', sa.String(length=10), nullable=True),
    sa.Column('target_language', sa.String(length=10), nullable=True),
    sa.Column('message_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_translate_sessions_id'), 'live_translate_sessions', ['id'], unique=False)
    op.create_table('live_translate_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('speaker', sa.String(length=20), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=True),
    sa.Column('translated_text', sa.Text(), nullable=True),
    sa.Column('is_final', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['live_translate_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_live_translate_messages_id'), 'live_translate_messages', ['id'], unique=False)
    op.create_index(op.f('ix_live_translate_messages_session_id'), 'live_translate_messages', ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.drop_index(op.f('ix_live_translate_messages_session_id'), table_name='live_translate_messages')
    op.drop_index(op.f('ix_live_translate_messages_id'), table_name='live_translate_messages')
    op.drop_table('live_translate_messages')
    op.drop_index(op.f('ix_live_translate_sessions_id'), table_name='live_translate_sessions')
    op.drop_table('live_translate_sessions')
    # ### end Alembic commands ###
